version: '3.8'
services:

  db:
    image: postgres
    container_name: store_portfolio
    restart: always
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - vol_postgres:/var/lib/postgresql/data
volumes:
  vol_postgres: