version: '3.8'
services:

  app:
    image: yoandevelop/store-app-api:v1
    build:
      context: .
    command: sh -c 'sleep 10; npm start'
    env_file:
      - ./src/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - store_network

  db:
    image: postgres
    container_name: storedb
    restart: always
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    volumes:
      - vol_postgres:/var/lib/postgresql/data
    networks:
      - store_network

networks:
  store_network:
volumes:
  vol_postgres: