apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: store-api
spec:
  selector:
    matchLabels:
      app: api-store
  template:
    metadata:
      labels:
        app: api-store
    spec:
      containers:
      - name: api-store
        image: yoandevelop/store-app-api:v1
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: JWT_SECRET
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: api-store 
            containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: api-store-svc
spec:
  type: NodePort
  selector:
    app: api-store
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30100
